title: Kayla Cho # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Rising Senior at Chapman University 
  <br><br>
  Business Administration with an Emphasis in Finance & Entreprenurship with a Minor in Data Analytics 
  <br><br>
  <a href="https://www.linkedin.com/in/kayla-cho/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
