title: Kayla Cho # your name (or website title) here
logo: "images/1570846917433.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior at Chapman University 
  Expected Graduation: Spring 2022
  <br><br>
  Business Administration with an Emphasis in Finance & Entreprenurship 
  
  Minor in Data Analytics 
  <br><br>
  <a href="mailto:kaayla.cho@gmail.com">Email Me</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/kayla-cho/">View My LinkedIn Profile</a> 
 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
